added login and reg
xerxes-on/pet_project_front pull request #2
Opened 2024-09-04 11:50 UTC by xerxes-on

2024-09-04 12:08 UTC, volhaliferovich commented on src/api/client.js
> +        baseURL: 'http://bookrating.test/api/'
Remove "/" at the end of your base url if you want to use "/books"

2024-09-04 12:08 UTC, volhaliferovich commented on src/components/common/Svg.vue
> +import {defineProps, ref} from "vue";
You don't need to import defineProps, it's a compiler macro. Remove it from here

2024-09-04 12:08 UTC, volhaliferovich commented on src/plugins/index.js
> +const loading = ref(false)
Losing shouldn't be here, if you want to create a global loading variable, create a new store under the store folder and initialise it there

2024-09-04 12:08 UTC, volhaliferovich commented on src/plugins/index.js
> +    app.provide('loading', loading);
remove this

2024-09-04 12:10 UTC, xerxes-on commented on src/api/client.js
> +        baseURL: 'http://bookrating.test/api/'
ok

2024-09-04 12:10 UTC, xerxes-on commented on src/components/common/Svg.vue
> +import {defineProps, ref} from "vue";
ok

2024-09-04 12:12 UTC, xerxes-on commented on src/plugins/index.js
> +    app.provide('loading', loading);
removed

2024-09-04 12:52 UTC, volhaliferovich commented on src/App.vue
> +import {RouterView} from 'vue-router'
You don't need to import RouterView, it's available without it

2024-09-06 05:13 UTC, volhaliferovich requested changes

2024-09-06 05:13 UTC, volhaliferovich commented on src/router/index.js
> +    if (!isAuthenticated && (to.name !== 'login' ||) ) {
You haven't finished the condition here, please fix, even if you already did it in a different branch

2024-09-06 05:13 UTC, volhaliferovich commented on .prettierrc.json
> +    "singleQuote": true
Please add these rules:  "trailingComma": "es5", "printWidth": 180. And run "npm run format" again.

2024-09-06 05:13 UTC, volhaliferovich commented on src/components/loginComponents/LoginForm.vue
> +import { useErrorPop } from '@/stores/index.js'
Always remove unused imports.

2024-09-06 05:13 UTC, volhaliferovich commented on src/components/loginComponents/RegisterForm.vue
> +import { useRouter } from 'vue-router'
Change the order of imports everywhere. You should sort them from vue imports to your own custom ones (vue, vue-router, vuelidate, your stores/api, your components)

2024-09-06 05:13 UTC, volhaliferovich commented on src/views/Register.vue
> +import Logo from '@/components/common/Logo.vue'
Unused imports, LoginForm as well.

2024-09-06 05:13 UTC, volhaliferovich commented on index.html
> +        <script src="https://cdn.tailwindcss.com"></script>
You already have tailwindcss in your package.json. You should go either with npm installations, or cdn.

2024-09-06 09:44 UTC, xerxes-on commented on src/api/client.js
> +// const authStore = useAuthStore();
okay

2024-09-06 09:48 UTC, xerxes-on commented on .prettierrc.json
> +    "singleQuote": true
done

2024-09-06 10:41 UTC, volhaliferovich approved these changes

2024-09-06 10:42 UTC, merged